services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: epay/php-fpm:latest
    environment:
      TZ: Asia/Shanghai
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: epay
      DB_PASSWORD: supersecret
      DB_NAME: epay
      DB_PREFIX: pay
    volumes:
      - php-sessions:/var/lib/php/sessions
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-m"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: epay/nginx:latest
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - php
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: epay
      MYSQL_USER: epay
      MYSQL_PASSWORD: supersecret
      MYSQL_ROOT_PASSWORD: changeme
      TZ: Asia/Shanghai
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    ports:
      - "33060:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
  php-sessions:
